version: '3'
name: tmwu_authentication_api_dev
services:
  api:
    container_name: tmwu_authentication_api_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - '5000:5000'
    volumes:
      - ./src:/app/src
    expose:
      - '5000'
