version: '3'
name: auth_api_dev
services:
  api:
    container_name: auth_api_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - '9000:9000'
    volumes:
      - ./src:/app/src
    expose:
      - '9000'
