version: '3'
name: tmwu_authentication_api
services:
  api:
    container_name: tmwu_authentication_api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '6000:6000'
    volumes:
      - ./src:/app/src
    expose:
      - '6000'
